"""Paper analysis: tables and figures from the saved field trajectories.

The experiment driver stores per-checkpoint scalars, but the saved field files
(``fields_<problem>_<config>.npz``) contain the full predicted and true
trajectories, so every metric and figure here is recomputed from the fields at
whatever checkpoints we want - including t = 300, 400, 500.

Outputs (results_paper/):
    TABLES.md                    markdown tables ready to paste into the paper
    fig_rms_time_<p>.png         relative RMS vs rollout time, all models
    fig_pred_vs_real_<p>.png     actual vs predicted at t = 100..500, all models
    fig_scaling.png              best-vs-best parameter scaling curves
    fig_verdict_<metric>.png     verdict / metric heatmap, models x equations

Run:  python -m track2.paper_analysis
"""
from __future__ import annotations

import argparse
import glob
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch

from .metrics import amplitude_ratio, classify, pattern_correlation, rel_rms

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results_paper")
CPS = [100, 200, 300, 400, 500]
ORDER = ["advection", "heat", "wave1d", "burgers", "kdv", "wave2d"]
CLIP = 1e3


def load_fields(problem, name):
    f = os.path.join(RES, f"fields_{problem}_{name}.npz")
    if not os.path.isfile(f):
        return None, None
    try:  # a truncated/corrupt .npz must skip its row, not kill the whole figure
        z = np.load(f)
        return torch.from_numpy(z["pred"]), torch.from_numpy(z["truth"])
    except Exception as e:
        print(f"  warn: unreadable {os.path.basename(f)}: {e}")
        return None, None


def configs_for(problem):
    f = os.path.join(RES, f"paper_{problem}_b25000_s0.json")
    if not os.path.isfile(f):
        f = os.path.join(RES, f"paper_{problem}_b25000_s0_sub.json")
    if not os.path.isfile(f):
        return {}, {}
    d = json.load(open(f))
    return {k: v for k, v in d.items() if k != "_meta"}, d["_meta"]


def curve(pred, truth, stride=5):
    ts, rs = [], []
    T = min(pred.shape[0], truth.shape[0])
    for t in range(0, T, stride):
        ts.append(t)
        rs.append(min(rel_rms(pred[t], truth[t]), CLIP) if torch.isfinite(pred[t]).all() else CLIP)
    return np.array(ts), np.array(rs)


# ---------------------------------------------------------------------------
def build_tables():
    lines = ["# Paper tables (auto-generated by track2.paper_analysis)", ""]
    summary = {}
    for prob in ORDER:
        cfgs, meta = configs_for(prob)
        if not cfgs:
            continue
        cps = [c for c in CPS if c <= meta["t_out"]]
        lines += [f"## {prob}  (N={meta['n_traj']}, rollout={meta['t_out']}, "
                  f"budget={meta['budget']:,}, epochs={meta['epochs']})", "",
                  "| model | params | mode | UH | last-good | "
                  + " | ".join(f"RMS t={c}" for c in cps)
                  + " | corr t=" + str(cps[-1]) + " | amp t=" + str(cps[-1]) + " | verdict |",
                  "|---|---:|---|---:|---:|" + "---:|" * (len(cps) + 2) + "---|"]
        rows = []
        for name, v in cfgs.items():
            pred, truth = load_fields(prob, name)
            if pred is None:
                continue
            vals = []
            for c in cps:
                if c < pred.shape[0] and torch.isfinite(pred[c]).all():
                    vals.append(rel_rms(pred[c], truth[c]))
                else:
                    vals.append(float("inf"))
            cl = min(cps[-1], pred.shape[0] - 1)
            co = pattern_correlation(pred[cl], truth[cl]) if torch.isfinite(pred[cl]).all() else float("nan")
            am = amplitude_ratio(pred[cl], truth[cl]) if torch.isfinite(pred[cl]).all() else float("nan")
            rows.append((name, v, vals, co, am))
            summary.setdefault(prob, {})[name] = {
                "rms": vals, "corr": co, "amp": am, "params": v["params"],
                "uh": v["usable_horizon"], "last_good": v.get("last_good_step", 0),
                "verdict": classify(co, am)}
        rows.sort(key=lambda r: r[2][min(1, len(r[2]) - 1)])
        for name, v, vals, co, am in rows:
            fmt = lambda x: ("**" + f"{x:.4g}" + "**") if x < 0.1 else (f"{x:.4g}" if np.isfinite(x) else "div")
            lines.append(f"| `{name}` | {v['params']:,} | {v['mode']} | "
                         f"{v['usable_horizon']} | {v.get('last_good_step',0)} | "
                         + " | ".join(fmt(x) for x in vals)
                         + f" | {co:.3f} | {am:.3f} | {classify(co, am)} |")
        lines.append("")
    with open(os.path.join(RES, "TABLES.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote TABLES.md")
    return summary


def fig_rms_time():
    for prob in ORDER:
        cfgs, meta = configs_for(prob)
        if not cfgs:
            continue
        fig, ax = plt.subplots(figsize=(9, 5.4))
        for name in cfgs:
            pred, truth = load_fields(prob, name)
            if pred is None:
                continue
            t, r = curve(pred, truth)
            ls = {"recursive": "-", "seq2seq": "--", "direct": ":"}[cfgs[name]["mode"]]
            ax.plot(t, np.clip(r, 1e-5, CLIP), ls, lw=1.7, label=name)
        ax.set_yscale("log"); ax.axhline(1.0, color="k", ls=":", alpha=0.6)
        ax.axhline(0.2, color="grey", ls=":", alpha=0.6)
        ax.set_xlabel("rollout step"); ax.set_ylabel("relative RMS (log)")
        ax.set_title(f"{prob} — RMS vs rollout time (matched ~25k params, N={meta['n_traj']})",
                     fontweight="bold")
        ax.grid(alpha=0.3, which="both"); ax.legend(fontsize=7, ncol=2)
        fig.tight_layout()
        fig.savefig(os.path.join(RES, f"fig_rms_time_{prob}.png"), dpi=135)
        plt.close(fig)
        print(f"wrote fig_rms_time_{prob}.png")


def fig_pred_vs_real():
    pred_order = ORDER + (["wave3d"] if "wave3d" not in ORDER else [])
    for prob in pred_order:
        cfgs, meta = configs_for(prob)
        if not cfgs:
            continue
        names = [n for n in cfgs if load_fields(prob, n)[0] is not None]
        if not names:
            continue
        cps = [c for c in CPS if c <= meta["t_out"]]
        if len(cps) < 3:  # 2-D/3-D rollouts are short; sample the trajectory instead
            T = meta["t_out"]
            cps = [max(1, int(T * f)) for f in (0.2, 0.4, 0.6, 0.8, 1.0)]
        is2d = prob == "wave2d"
        is3d = prob == "wave3d"
        img = is2d or is3d
        def plane(a):  # 3-D volume -> mid-plane z-slice; 1-D/2-D unchanged
            return a[:, :, a.shape[-1] // 2] if is3d else a
        nrow, ncol = len(names) + 1, len(cps)
        fig, axes = plt.subplots(nrow, ncol, figsize=(2.5 * ncol, 1.65 * nrow), squeeze=False)
        _, truth = load_fields(prob, names[0])
        vm = float(truth[0, 0, 0].abs().max()) if img else float(truth[:, 0, 0].abs().max())
        for j, c in enumerate(cps):
            ax = axes[0][j]
            if img:
                ax.imshow(plane(truth[c, 0, 0]).T, origin="lower", cmap="seismic", vmin=-vm, vmax=vm)
                ax.set_xticks([]); ax.set_yticks([])
            else:
                ax.plot(truth[c, 0, 0], "k", lw=1.6); ax.set_ylim(-vm * 1.4, vm * 1.4)
                ax.set_xticks([]); ax.set_yticks([])
            ax.set_title(f"t={c}", fontsize=9)
            if j == 0:
                ax.set_ylabel("TRUTH", fontsize=7, fontweight="bold")
        for i, name in enumerate(names):
            pred, truth = load_fields(prob, name)
            for j, c in enumerate(cps):
                ax = axes[i + 1][j]
                ax.set_xticks([]); ax.set_yticks([])
                if c >= pred.shape[0]:
                    ax.axis("off"); continue
                p = pred[c, 0, 0]
                if not torch.isfinite(p).all():
                    ax.text(0.5, 0.5, "diverged", ha="center", va="center",
                            fontsize=7, color="red", transform=ax.transAxes); continue
                if img:
                    ax.imshow(plane(p).T.clamp(-CLIP, CLIP), origin="lower", cmap="seismic", vmin=-vm, vmax=vm)
                else:
                    ax.plot(truth[c, 0, 0], "k", lw=1.0, alpha=0.4)
                    ax.plot(p.clamp(-CLIP, CLIP), "r", lw=1.2)
                    ax.set_ylim(-vm * 1.4, vm * 1.4)
                if j == 0:
                    ax.set_ylabel(name, fontsize=6, fontweight="bold")
        extra = "  (mid-plane z-slice)" if is3d else ""
        fig.suptitle(f"{prob} — actual (black) vs predicted (red), matched ~25k params{extra}",
                     fontweight="bold", y=0.997)
        fig.tight_layout(rect=[0, 0, 1, 0.985])
        fig.savefig(os.path.join(RES, f"fig_pred_vs_real_{prob}.png"), dpi=130)
        plt.close(fig)
        print(f"wrote fig_pred_vs_real_{prob}.png")


def fig_scaling():
    budgets = [6000, 25000, 100000, 400000]
    probs = ["burgers", "kdv"]
    fig, axes = plt.subplots(1, len(probs), figsize=(6.2 * len(probs), 5.0), squeeze=False)
    for ax, prob in zip(axes[0], probs):
        for fam, col in (("skino_noise", "#d62728"), ("fno_noise", "#1f77b4")):
            xs, ys = [], []
            for b in budgets:
                f = os.path.join(RES, f"paper_{prob}_b{b}_s0_sub.json")
                if not os.path.isfile(f):
                    continue
                d = json.load(open(f))
                if fam not in d:
                    continue
                cp = str(d["_meta"]["checkpoints"][-1])
                xs.append(d[fam]["params"])
                ys.append(min(d[fam]["metrics"].get(cp, {}).get("rel_rms", np.nan), CLIP))
            if xs:
                ax.plot(xs, ys, "o-", color=col, lw=2, ms=8, label=fam)
                ax.annotate(f"best {min(ys):.3g}", (xs[int(np.argmin(ys))], min(ys)),
                            fontsize=8, xytext=(6, -12), textcoords="offset points", color=col)
        ax.set_xscale("log"); ax.set_yscale("log")
        ax.set_xlabel("trainable parameters (log)"); ax.set_ylabel("relative RMS @ t=200 (log)")
        ax.set_title(f"{prob} — accuracy vs budget\n(each family at its own best size)",
                     fontweight="bold")
        ax.grid(alpha=0.3, which="both"); ax.legend(fontsize=9)
    fig.suptitle("Best-vs-best parameter scaling (identical training budget)", fontweight="bold")
    fig.tight_layout()
    fig.savefig(os.path.join(RES, "fig_scaling.png"), dpi=140); plt.close(fig)
    print("wrote fig_scaling.png")


def fig_heatmap(summary):
    names = []
    for prob in ORDER:
        for n in summary.get(prob, {}):
            if n not in names:
                names.append(n)
    probs = [p for p in ORDER if p in summary]
    M = np.full((len(names), len(probs)), np.nan)
    for j, p in enumerate(probs):
        for i, n in enumerate(names):
            if n in summary[p]:
                v = summary[p][n]["rms"][1] if len(summary[p][n]["rms"]) > 1 else summary[p][n]["rms"][0]
                M[i, j] = min(v, CLIP)
    fig, ax = plt.subplots(figsize=(1.5 * len(probs) + 4.5, 0.42 * len(names) + 2.4))
    im = ax.imshow(np.log10(M), cmap="RdYlGn_r", aspect="auto", vmin=-2, vmax=0.5)
    ax.set_xticks(range(len(probs))); ax.set_xticklabels(probs, fontweight="bold", rotation=20)
    ax.set_yticks(range(len(names))); ax.set_yticklabels(names, fontsize=8)
    for i in range(len(names)):
        for j in range(len(probs)):
            if np.isnan(M[i, j]):
                ax.text(j, i, "-", ha="center", va="center", color="grey"); continue
            txt = "div" if M[i, j] >= CLIP else f"{M[i,j]:.3f}"
            ax.text(j, i, txt, ha="center", va="center", fontsize=7,
                    color="black" if M[i, j] < 0.6 else "white")
    fig.colorbar(im, ax=ax, label="log10( relative RMS @ t=200 )")
    ax.set_title("Rollout accuracy at matched ~25k parameters\ngreen = good, red = broken",
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(os.path.join(RES, "fig_verdict_heatmap.png"), dpi=140); plt.close(fig)
    print("wrote fig_verdict_heatmap.png")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-dir", default=None,
                    help="folder with paper_*.json + fields_*.npz (default: results_paper)")
    ap.add_argument("--only", default=None,
                    help="comma list of figures to build: tables,rms,pred,scaling,heatmap")
    a = ap.parse_args(argv)
    global RES
    if a.results_dir:
        cand = a.results_dir
        if not os.path.isdir(cand):
            cand = os.path.join(HERE, os.path.basename(a.results_dir.rstrip("/\\")))
        RES = os.path.abspath(cand)
    print(f"results dir: {RES}")
    only = set(a.only.split(",")) if a.only else {"tables", "rms", "pred", "scaling", "heatmap"}
    s = build_tables() if ("tables" in only or "heatmap" in only) else {}
    if "rms" in only:
        fig_rms_time()
    if "pred" in only:
        fig_pred_vs_real()
    if "scaling" in only:
        fig_scaling()
    if "heatmap" in only:
        fig_heatmap(s)


if __name__ == "__main__":
    main()
